### ISSUE TITLE
Double prefix judul MRHANDS DROPSHIP 1.3.3

### ISSUE THREAD

**Issue by zaiyin** [handita/mdsreport#2]
Bug: Prefix judul MDS versi 1.3.3 keluar dua kali 

https://prnt.sc/m5b4mg

**Comment by handita** [comment]
Bisa kirimin backup data mas.. ke fb ane ya.. https://m.me/handitaokviyanto

**Comment by handita** [comment]
Sudah selesai masalahnya ya.. di 1.3.4
