### ISSUE TITLE
SKU Aliexpress

### ISSUE THREAD

**Issue by naim03** [handita/mdsreport#3]
sku aliexpress sebagian muncul sebagian tidak,dan produk terposting double,mohon perbaikannya!

#aliexpres#sku

**Comment by handita** [comment]
Bisa kasih contoh produknya? Dan hasilnya kyak gimana? Biar saya cek

**Comment by naim03** [comment]
![screenshot 1](https://user-images.githubusercontent.com/46613953/51067577-79e7b800-164e-11e9-9d9d-2648f642f5c8.png)
![screenshot 2](https://user-images.githubusercontent.com/46613953/51067578-79e7b800-164e-11e9-8253-be37ee69a0c5.png)
![screenshot](https://user-images.githubusercontent.com/46613953/51067579-7a804e80-164e-11e9-9267-3d28848017a6.png)

**Comment by handita** [comment]
Ini gak munculnya gmana ya SKUnya? kalo produk terposting dobel itu pilih export toped tanpa varian ya.. dengan varian akan membuat duplikasi sesuai varian

**Comment by handita** [comment]
close karena tidak aktif lagi
