### ISSUE TITLE
Mrhands Plugin Rusak di Google Chrome Linux

### ISSUE THREAD

**Issue by rullyiswanto** [handita/mdsreport#4]
Saya menggunakan **OS Linux Mint 19** dengan _browser_ Google chrome versi 71.0.3578.98. 
Saya menggunakan Mrhands versi 1.3.5 namun setelah mengisi _username_ dan _password_ utk _login
!
_ ekstensi ini langsung _crash_ dan muncul di halaman ekstensi dengan tulisan **"ekstensi ini mungkin rusak"**. ![mrshand rusak](https://user-images.githubusercontent.com/19989998/51421218-263d1780-1bd6-11e9-877d-168f878d4f44.png) saya sudah mencoba untuk menghapus dan menginstal ulang. hasilnya tetap sama.
Apakah memang ekstensi ini hanya bisa di gunakan di chrome windows. Tolong solusinya

**Comment by handita** [comment]
Maaf mas.. baru balas.. kalo lama bisa ke group support fb dlu ya..
ikuti lagi aja tutorial dari  halaamn member area mrhands
