### ISSUE TITLE
Button import di shopee tidak bekerja 

### ISSUE THREAD

**Issue by cumironin** [handita/mdsreport#8]
Beberapa kali saya refresh chrome, button import list (warna ungu) di marketplace shopee tidak bekerja.

Note : 
- Button tidak mau di tekan
- Mr.hand 1.4.2

**Comment by handita** [comment]
Versi chrome berapa?? Coba masuk ke chrome://extensions

Kalo ada errors clear errors

**Comment by cumironin** [comment]
Version 70.0.3538.77 (Official Build) (64-bit)

No error

**Comment by cumironin** [comment]
> Versi chrome berapa?? Coba masuk ke chrome://extensions Kalo ada errors clear errors

ok, working... update ke Version 73.0.3683.86 (Official Build) (64-bit)
silahkan di close, trims

**Comment by handita** [comment]
Siapp close ya
